### ISSUE TITLE
Backlink doesn't work properly

### ISSUE THREAD

**Issue by tarant75** [kelson42/swissinfodesk#1]
The backlink should open a new section. The link is that one: https://de.wikipedia.org/w/index.php?title=Diskussion:Schweizerische_Nationalbibliothek&action=edit&section=new&preload=Vorlage:$1&preloadparams%5B%5D=%40%5B%5BBenutzer%3ASwissInfoDesk%7CSwissInfoDesk%5D%5D%3A+%3Cbitte+diesen+Text+in+eckigen+Klammern+mit+der+Frage+ersetzen.%3E+--%7E%7E%7E%7E&preloadtitle=Frage+an+SwissInfoDesk

It works if you try it in the browser. If it is via kiwik server it doesn't work. You find the example here:

https://de.wikipedia.org/wiki/Diskussion:Schweizerische_Nationalbibliothek

**Comment by kelson42** [comment]
@tarant75 You should url_encode the "back" value. Here is how it should looks like: http://wiki.kiwix.org/swissinfodesk/?title=Schweizerische_Nationalbibliothek&lang=de&back=https%3A%2F%2Fde.wikipedia.org%2Fw%2Findex.php%3Ftitle%3DDiskussion%3ASchweizerische_Nationalbibliothek%26action%3Dedit%26section%3Dnew%26preload%3DVorlage%3A%241%26preloadparams%255B%255D%3D%2540%255B%255BBenutzer%253ASwissInfoDesk%257CSwissInfoDesk%255D%255D%253A%2B%253Cbitte%2Bdiesen%2BText%2Bin%2Beckigen%2BKlammern%2Bmit%2Bder%2BFrage%2Bersetzen.%253E%2B--%257E%257E%257E%257E%26preloadtitle%3DFrage%2Ban%2BSwissInfoDesk

have a look to https://www.mediawiki.org/wiki/Help:Magic_words/fr#URL_data
